### PR TITLE
Reorder management command fixed

### PR DESCRIPTION
**Pull request by djb15**
When integrating this module into my django project the reorder command wouldn't work as indicated in the docs.  From the terminal I would run the following command:
screen shot 2016-08-20 at 20 40 35
This throws the unrecognised arguments error as shown.

Following my fix the code now runs correctly as shown here:
screen shot 2016-08-20 at 20 43 03

I hope this helps and if you have any questions please feel free to ask.
Thanks for the great piece of software!

### CODE REVIEW

**Comment by jrief** [comment]
In Django, if you want to name a model, you would rather use ``services.InfoBox`` not ``services.models.InfoBox``. Please recheck and if this helps, please close this issue.

**Comment by djb15** [comment]
Using your advice as stated above I still run into the the same issue:
screen shot 2016-08-22 at 21 09 34

**Comment by jrief** [comment]
Could you then please paste the complete stack on https://dpaste.de/

**Comment by djb15** [comment]
My directory structure is as follows:

├── db.sqlite3
├── manage.py
├── media
│   └── ...
├── priory_lodge
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── settings.py
│   ├── settings.pyc
│   ├── urls.py
│   ├── urls.pyc
│   ├── wsgi.py
│   └── wsgi.pyc
├── root
│   ├── ...
├── services
│   ├── __init__.py
│   ├── __init__.pyc
│   ├── admin.py
│   ├── admin.pyc
│   ├── apps.py
│   ├── apps.pyc
│   ├── forms.py
│   ├── migrations
│   │   ├── ...
│   ├── models.py
│   ├── models.pyc
│   ├── templates
│   │   └── services
│   │       ├── ...
│   ├── tests.py
│   ├── urls.py
│   ├── urls.pyc
│   ├── views.py
│   └── views.pyc
├── static
│   └── priory_lodge
│       ├── ...
└── templates
    └── priory_lodge
        └── ...

I have pasted the relevant files below:

https://dpaste.de/6V6p - models.py
https://dpaste.de/FwgX - admin.py
https://dpaste.de/08m5 - settings.py

I hope this is sufficient information to help!

**Comment by jrief** [comment]
strange that it worked for me and other all the time.
Just for curiosity, which version of Django do you use?

**Comment by djb15** [comment]
For this project I am using Django 1.10.  Thanks for the great first experience with a pull request!

**Comment by jrief** [comment]
Django-1.10. Ah that's probably the reason it didn't work.

**Pull request merged**
