### PR TITLE
Support Django2.1

### PR DESCRIPTION
**Pull request by DingGGu**
On Django 2.1,

Django Admin will upgrade jQuery version.
> jQuery is upgraded from version 2.2.3 to 3.3.1.
https://docs.djangoproject.com/en/2.1/releases/2.1/#django-contrib-admin

and `$().context` was removed on jQuery 3.0 (deprecated on 1.10)
> https://api.jquery.com/context/

### CODE REVIEW

**Comment by DingGGu** [comment]
Currently, Django 2.1 is release candidate state now.
> https://code.djangoproject.com/wiki/Version2.1Roadmap#process

When Django 2.1 is stable, I will add it CI configuration.

**Comment by DingGGu** [comment]
I checked that it works also well on Django 1.8.
@jrief

**Comment by jrief** [comment]
@DingGGu great and thanks!

**Comment by DingGGu** [comment]
Could you release this version to pypi?
@jrief

**Pull request merged**
