### PR TITLE
Add support for generic inlines with SortableGenericInlineAdminMixin.

### PR DESCRIPTION
**Pull request by trevoriancox**

### CODE REVIEW

**Comment by jrief** [comment]
Please explain what this pull request is intended for. Just from reading the code, I don't understand your intentions.

**Comment by trevoriancox** [comment]
Currently the code assumes that inlines to be sorted will be either StackedInline or TabularInline. This pull request is to add support for Django's GenericStackedInline / GenericTabularInline. #issue253

**Comment by sixthgear** [comment]
I can confirm, GenericTabularInline does not seem to play well with SortableInlineAdminMixin. I'm going to test this PR to see if it helps my specific case.

Simple example of non-patched behavior in Django 3.1.3:

```python
# models.py

from django.db import models
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class Photo(models.Model):
    """
    A Photograph which can be m2m related to multiple different models using the Django contenttypes framework:
    https://docs.djangoproject.com/en/3.1/ref/contrib/contenttypes/
    """
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    # ...
    image = models.ImageField()

class Equipment(models.Model):
    """
    A piece of equipment with a generic m2m relation to Photo
    """
    # ...
    photos = GenericRelation(Photo)
```

```python
# admin.py

from django.contrib import admin
from django.contrib.contenttypes.admin import GenericTabularInline
from adminsortable2.admin import SortableInlineAdminMixin

class PhotoInline(SortableInlineAdminMixin, GenericTabularInline):
    """
    Inline to show photos for any other model.
    """
    model = Photo

@admin.register(Equipment)
class EquipmentAdmin(admin.ModelAdmin):
    """
    ModelAdmin for equipment.
    """
    inlines = [PhotoInline]
```

Accessing this admin gives an AttributeError: `type object 'PhotoFormFormSet' has no attribute 'fk'`. Traceback for reference:

```
Traceback (most recent call last):
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1598, in _changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1955, in _create_formsets
    prefix = FormSet.get_default_prefix()
  File "/Users/joshua/.local/share/virtualenvs/catalog-api-_WHHY7Or/lib/python3.8/site-packages/django/forms/models.py", line 944, in get_default_prefix
    return cls.fk.remote_field.get_accessor_name(model=cls.model).replace('+', '')

Exception Type: AttributeError at /admin/catalog/equipment/7951/change/
Exception Value: type object 'PhotoFormFormSet' has no attribute 'fk'
```

**Comment by sixthgear** [comment]
Unfortunately my example still fails in the same way when using the branch from @trevoriancox. Perhaps I'm not forming my example correctly? @trevoriancox can you help guide me, or perhaps show your own example of how to use your improvement?

**Comment by sixthgear** [comment]
Scratch that! I forgot to use the new SortableGenericInlineAdminMixin class provided by @trevoriancox. After doing so, I noticed a missing import in `adminsortable2/admin.py` line 41:

`from django.contrib.contenttypes.admin import GenericStackedInline`

In my case, I got a NameError because you reference GenericTabularInline on line 549. When I included that import everything worked as expected. Could you make that change @trevoriancox?

**Comment by sixthgear** [comment]
Example of the code working. You can see the reorder handles on the sides and drag and drop works great.

image

**Comment by trevoriancox** [comment]
@sixthgear I have added this missing GenericTabularInline import. Thanks for catching that!

**Comment by jrief** [comment]
OK, will merge this as soon as I have time to test it and add a unit test. If someone else wants to do that, even better!

**Comment by sixthgear** [comment]
> OK, will merge this as soon as I have time to test it and add a unit test. If someone else wants to do that, even better!

Hey @jrief I will write a test.

**Comment by sixthgear** [comment]
@jrief quick question for you regarding test coverage. 

The current test suite doesn't appear to be covering the existing `SortableInlineAdminMixin` at the moment. The testing app uses model `SortableBook` to test `SortableAdminMixin` extensively but doesn't appear to test the `Chapter` model which would be needed to test `SortableInlineAdminMixin`.

Am I correct in that assessment? If so it affects my confidence in writing an adequate test for the generic version, which I see as an extended case of the standard inline support.

**Comment by jrief** [comment]
For my better understanding, it would be great if I could see an example where the current implementation is problematic. I then might jump upon that I try to find a solution. [django-polymorphic](https://pypi.org/project/django-polymorphic/) would be a good point to start with, since it internally uses generic foreign keys.

Such an example is also good for the documentation.

**Comment by sixthgear** [comment]
I can provide that, give me a moment.

**Comment by sixthgear** [comment]
@jrief I forked from master and modified testapp to provide the problematic test case (similar to what I described in the comment above). I modified the existing `Notes` model to be a generic relation for Authors and SortableBooks, which I though was an appropriate application (and the existing testing coverage didn't appear to rely on Notes being a simple fk relation).

https://github.com/sixthgear/django-admin-sortable2/tree/feature/generic

**Comment by sixthgear** [comment]
@jrief Did my example shed any light for you?

**Comment by sixthgear** [comment]
@jrief is there anything else I can do to help get this feature merged beyond the examples and test case I provided above?

**Comment by jrief** [comment]
Thanks. I will try this out.

**Pull request merged**
