### PR TITLE
Extend test suite to django 3.2

### PR DESCRIPTION
**Pull request by marksweb**
I've extended the test suite to include django 3.2.

I'm also keen to remove EOL python versions; 2.7, 3.4, 3.5 and add 3.9.

### CODE REVIEW

**Comment by marksweb** [comment]
@jrief This might be worth merging & preparing a release. I've updated use of `url()` to `path()` as well to cover deprecation warnings

**Review by jhernandez-at-wiris — APPROVED** [review]
It works fine when I test it

**Comment by sudhirakash** [comment]
Can we merge this Pull request soon? We really want support for django 3.2.

**Comment by marksweb** [comment]
> Can we merge this Pull request soon? We really want support for django 3.2.

I've merged it. I'm not sure when I'll get chance to release it at the moment but you could install from the branch for now.

**Comment by sudhirakash** [comment]
Hi Mark,

Thanks for merging the commit, As I am trying to use his package in a high-level production, can you please help me in getting a new release tag with this feature. I really appreciate your prompt response.

Thanks

**Comment by marksweb** [comment]
> Hi Mark,
> 
> Thanks for merging the commit, As I am trying to use his package in a high-level production, can you please help me in getting a new release tag with this feature. I really appreciate your prompt response.
> 
> Thanks

Hi @sudhirakash

I can't be sure when I'll have time to tag & release to pypi due to family commitments over the next 2 weeks.

I can't see any code changing though besides the change log and version number. So until we get round to releasing, installing from master would be your best bet.

**Pull request merged**
