### PR TITLE
Fix reverse ordering for ChangList, StackedInline and TabularInline

### PR DESCRIPTION
**Pull request by svleeuwen**
This PR fixes multiple issues with reverse ordering.

### CODE REVIEW

**Comment by jrief** [comment]
Thanks for this huge pull request. Please give me some time to review it properly.

@kayadata could you please review this PR in your current setup and check if everything works fine.

**Comment by svleeuwen** [comment]
Of course.

Please note that for `ChangeList` this only works consistently when the ordering column is the first one in `model_admin.list_display`. (or not specified which means it's prepended automatically)

'Other-column-sorting' not working is a separate issue that's also present in the currently released version.

**Comment by kayadata** [comment]
i can confirm that this pr fixes issue #154

**Comment by jrief** [comment]
OK. So let's trust @kayadata for his review and thanks to @svleeuwen for his pull request.

**Comment by jrief** [comment]
@svleeuwen please add a line or two for the changelog, either here or directly on the file.

**Comment by svleeuwen** [comment]
Changelog:

Fixes #154 and #143: When ordering is reversed on `model._meta` or `admin.admin_model`, Django defaults the order to a negative value. Use this as a default in `list-sortable.js`.
Use the same information to reverse the ordering for inline admins in `inline-sortable.js`.

**Pull request merged**
