### PR TITLE
refactor: use jQuery from django instead of global jQuery

### PR DESCRIPTION
**Pull request by Flui**
First django.jQuery will be assigned to the inner $ and after I am waiting for the document to be loaded

### CODE REVIEW

**Comment by jrief** [comment]
@mkoistinen I remember that especially because of django-CMS, we had to add some tweaks, since the CMS used its own version of jQuery.
Did you remember those problem and do they cause trouble here?

**Comment by Flui** [comment]
There is really just basic jQuery used. And in inline-tabular.js django.jQuery was already used.

**Comment by jrief** [comment]
@Flui 
The way you did it, caused errors in my browser.

I now removed the first invocation of the functions, and now everything works fine. Please recheck, do a pull from the master branch and let me know.

Why did you first add a functions to the jQuery namespace, and then call it again?

**Comment by jrief** [comment]
@Flui ping

**Comment by Flui** [comment]
Oh yeah sorry my fault.

**Comment by jrief** [comment]
has been fixed anyway.

**Pull request merged**
