### PR TITLE
Load JS in the proper order following changes in Django 2.2

### PR DESCRIPTION
**Pull request by daniviga**
Following recent changes introduced in Django 2.2 media JS are loaded using a different algorithm and dependencies must be explicitly declared.

After the proposed changes `adminsortable2/js/plugins/admincompat.js` strictly depends on `admin/js/jquery.init.js`, `adminsortable2/js/inline-sortable.js` depends on `adminsortable2/js/jquery.ui.sortable-1.11.4.js` and so on.

Before (not working with Django 2.2):

```html
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/plugins/admincompat.js"></script>
<script type="text/javascript" src="/static/admin/js/collapse.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/inline-sortable.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/inline-tabular.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.core-1.11.4.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.widget-1.11.4.js"></script>
[...]
```

After (works with Django 2.2 and older):
```html
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/collapse.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/plugins/admincompat.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.core-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.widget-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.mouse-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.sortable-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/inline-sortable.js"></script>
[...]
```
See https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets

### CODE REVIEW

**Comment by jrief** [comment]
Thanks for this pull request, I'm going to merge this.

Are you sure it will work until version 1.8? Otherwise I will drop support for the legacy versions of Django and increase the minor version number for the next release.

Since it's going to support Django-2.2, please change that in the `setup.py`.

**Comment by daniviga** [comment]
> Are you sure it will work until version 1.8? Otherwise I will drop support for the legacy versions of Django and increase the minor version number for the next release.

I was able to test i back to Django 1.6 and it worked well, Django was already smart enough:

```
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/plugins/admincompat.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.core-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.widget-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.mouse-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/libs/jquery.ui.sortable-1.11.4.js"></script>
<script type="text/javascript" src="/static/adminsortable2/js/list-sortable.js"></script>
```

> Since it's going to support Django-2.2, please change that in the `setup.py`.

Done, I've also added Python 3.7 since my application is actually already running on Python 3.7

**Comment by jrief** [comment]
do you have any idea why this test fails?
https://travis-ci.org/jrief/django-admin-sortable2/jobs/516088000

it's the only one in this configuration, hmmmm....

**Comment by daniviga** [comment]
> do you have any idea why this test fails?

I was going to ask you the same...

I'll try to reproduce it locally

**Comment by daniviga** [comment]
I run several tests locally using Python 3.5 (on a Fedora Linux) and out of 100 iterations it failed on 68: there's a race condition in loading the fixtures. Fixtures do not guarantee order at load time at it was happening that sometime `auth.permission` objects were already in the DB before loading the relevant part of the fixture. I fixed the issue cleaning up a bit the fixtures.

**Pull request merged**
