### PR TITLE
Fix #208 - unable to pass custom css classes then using StackedInline

### LINKED ISSUE #208: Inline "classes=collapse" option doesn't work with StackedInline
I'm trying to add an inline model admin that is collapsed by default, using the [`classes=('collapse',)` admin option:](https://docs.djangoproject.com/en/2.1/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.classes)

>  **InlineModelAdmin.classes**
> A list or tuple containing extra CSS classes to apply to the fieldset that is rendered for the inlines. Defaults to None. As with classes configured in fieldsets, inlines with a collapse class will be initially collapsed and their header will have a small “show” link.

Here is the example I'm using:

```
class FeatureInline(SortableInlineAdminMixin, admin.StackedInline):
    """Feature inline"""
    model = models.Feature
    extra = 0
    classes = ('collapse', )
```

which doesn't seem to work. There is no error, but the inline appears regularly (i.e. not collapsed). 

If I change to an `admin.TabularInline`, or if I remove `SortableInlineAdminMixin` altogether, the inline will correctly appear collapsed. 

I'm using Django 2.0.7 and the latest `django-admin-sortable2` (0.6.21)

### PR DESCRIPTION
**Pull request by wwarne**
I compared standart django's StackedInline template and django-admin-sortable2's template and found this little difference in layout.

Closes #208.

### CODE REVIEW

**Comment by jrief** [comment]
Please add this fix to the Changelog.

Against which version of Django did you test it?
I'm asking because Django sometimes changes its templates and in order to be compatible with all sorts of versions, django-admin-sortable2 has to reflect that.

**Comment by wwarne** [comment]
I've tested this only with django 2.2. 
I will try it with different django-versions (1.x and 2.x) and will write about results right here.

**Comment by wwarne** [comment]
I have manually tested `SortableInlineAdminMixin + StackedInline` on this versions of django:

- django 1.10 - ok

- django 1.11.26 - ok

- django 2.0.13 - ok

- django 2.1.14 - ok

- django 2.2.7 - ok

- django master branch - 3.1 f97a612 - ok

Everything worked fine (creating new elements, moving elements to different positions)

**Comment by jrief** [comment]
Ok, thanks.

**Pull request merged**
