### PR TITLE
Allow use on mobile devices

### PR DESCRIPTION
**Pull request by GHPS**
Fixes Issue #108.

### CODE REVIEW

**Comment by jrief** [comment]
Could you please use the unminified version of `jquery.ui.touch-punch.js`.
In Django there are plenty of ways to compress/uglify JS code, but in case someone has to debug anything, the unminified version is much more helpful. Thanks.

**Comment by jrief** [comment]
Thanks. However, I didn't test it myself.

**Comment by GHPS** [comment]
Great - thanks. Please close issue #108 as well.

**Comment by oxbits** [comment]
i am using `django-admin-sortable2==0.7.6` & i cannot drag & drop on an iphone using chrome _  do i have 2 do something special 2 get it 2 work on mobile browserz ?

**Comment by GHPS** [comment]
I just tested jquery.ui.touch-punch.js with Safari on the iPhone - works fine.

Did you try Safari?

**Comment by oxbits** [comment]
i tried django admin object list view in safari iphone.  

it does not work.

am i supposed to do something special to activate it ?

or should django-admin-sortable2 just work out of the box ?

i saw this `touchHandled = false` 

should it be true ?

**Comment by GHPS** [comment]
> i tried django admin object list view in safari iphone.

It should work - I just checked with Safari 13 on the iPhone.

> am i supposed to do something special to activate it ?

The setup is basically as described in the docs [1]:
1) Pip install the package then install the app in settings.py.
2) Assign an ordering field in the meta section of your model in models.py.
3) Import the package in admin.py and inherit the SortableAdminMixin
in your admin class. Make sure to display the ordering field with
list_display.

That's it.... 

1: https://django-admin-sortable2.readthedocs.io/en/latest/usage.html

**Comment by GHPS** [comment]
@jrief After our discussion about jquery.ui.touch-punch both versions
(normal and min) ended up in the repo. The minimized version
(jquery.ui.touch-punch.min-0.2.3.js) can be deleted now...

**Comment by oxbits** [comment]
@GHPS  
you say to use SortableAdminMixin
i am using SortableInlineAdminMixin
does your solution work with both or only one ?

**Pull request merged**
