### PR TITLE
Added support for parler TranslatableInlineModelAdmin subclasses

### PR DESCRIPTION
**Pull request by racitup**
Do you think these changes are robust enough?
I've only tested TranslatableTabularInline

### CODE REVIEW

**Comment by racitup** [comment]
Now fixed and tested with parler inline_tabs to check warning

**Comment by llann** [comment]
Is this dead?

**Comment by jrief** [comment]
ups, oversaw it.

Would it be possible to put the Parler part into a separate method? In my opinion, that would be much cleaner.

**Comment by llann** [comment]
Humm, I made a test, it looks like django-admin-sortable2 is also not usable with modeltranslation and the class TranslationTabularInline.

It make it Switch from that :

without sortable

to that :

with sortable and modeltrans

Probably some conflict in tabular override.

That's pretty sad as today many project need to be translated in many languages with different tools.

Maybe it would be good to have an overall relexion about that.

**Comment by jrief** [comment]
If I would apply your pull request, users of this **django-admin-sortable2** which do not use **django-parler**, would be out of luck. I don't think this is a good idea.

**Pull request closed without merging**
