### PR TITLE
Added change links in admin inlines

### PR DESCRIPTION
**Pull request by mariuszjamro**
Added display of change links in admin inlines so that setting `show_change_link = True` on `InlineModelAdmin` would work when using with `SortableInlineAdminMixin`.

### CODE REVIEW

**Comment by jrief** [comment]
Sound interesting! Could you please paste a screenshot of your admin backend. I'm somehow curios how it looks like.

**Comment by mariuszjamro** [comment]
It adds the "change" next to model label and "show on site" link. Looks like this:

sortable_inline

**Comment by jrief** [comment]
Thanks for this pull request, I actually didn't even know about this feature. Has this been added recently to Django?

**Comment by mariuszjamro** [comment]
Django 1.8 introduced that

https://docs.djangoproject.com/en/1.9/releases/1.8/#minor-features

**Pull request merged**
