### PR TITLE
fixes for Django 2.0

### PR DESCRIPTION
**Pull request by PetrDlouhy**
+ add Travis test in Django development (in allow-failrues mode)

### CODE REVIEW

**Comment by jrief** [comment]
Thanks for this PR, so I don't have to do it ;)

Anyway, do you mind waiting until Django-2.0 is released, so that the requirements file can point onto the official release?

**Comment by MRigal** [comment]
I would rather use another strategy with naming the django versions and thus also using dj20 as an alias for Django 2.0, now as beta and later as final version... You could merge it already now

**Comment by PetrDlouhy** [comment]
@jrief Django 2.0 is released now. I have updated this to use official 2.0 version in Travis. Can You please merge this and make PIP package?

**Comment by jrief** [comment]
Many thanks!

**Pull request merged**
