### PR TITLE
Multilevel sort

### PR DESCRIPTION
**Pull request by racitup**
PR for issue #120

### CODE REVIEW

**Comment by jrief** [comment]
I tried out your PR and I fully agree that multilevel sort would make a lot of sense.

Therefore I just refactored the provided example and used 

```
ordering = ('author', 'my_order')
```

for ``SortableBook``.

This however introduced other issues. For instance, when clicking onto one of the columns *MY ORDER* or *AUTHOR*, the draggable area disappears.

Could you please retest this app with your patch using the example with ``author`` as the first field to order. For that purpose, I just added a lot new books together with their authors available in  ``example/testapp/fixtures/data.json``.

**Comment by racitup** [comment]
Okay, am currently struggling with other shop-related things but will get to this sometime.

**Comment by racitup** [comment]
Confirmed, sorting on anything other than the first column on testapp with data-110 loaded or my project causes drag handle to disappear. The handle comes back if sorted ascending or descending by the first column. This seems to only be a problem on lists and not inlines.

Caused by the div element being removed:
`<div class="drag ui-sortable-handle" order="20">&nbsp;</div>`

**Comment by racitup** [comment]
I have confirmed this is **not** an issue with my PR. The drag handle disappears in the same way with the master `SortableAdminMixin` and `ordering = ['my_order']`

**Comment by jrief** [comment]
closing for inactivity

**Pull request closed without merging**
