### PR TITLE
1.0 prep

### PR DESCRIPTION
**Pull request by marksweb**
Preparation for 1.0

### CODE REVIEW

**Comment by jrief** [comment]
@marksweb Thanks for your pull request. One thing to note is, that my editor uses `.editorconfig` and there `max_line length = 119` as [proposed by the Django style guide](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#python-style).

Until a few minutes ago, there was a typo in that file though 🤔.

**Comment by marksweb** [comment]
Thanks for the info @jrief

I've always used 80. I'll have to check if there's a pycharm plugin to read those config files. I'll revert to longer lines & then it might be ready.

**Comment by jrief** [comment]
Yes, it's bundled as plugin into PyCharm and I use that all the time. 
That's quite important where I work, because it also works in other IDEs such as Visual Studio Code used by my colleges.

**Comment by marksweb** [comment]
@jrief yes I've switched to project specific settings and it's picked it up nicely. Should be able to complete this release prep tonight.

**Comment by jrief** [comment]
As far as I have seen, this pull request just replaces formatting such as `'{x}'.format(x=9)` against `f'{x}'`. This means that Python-3.6 now is a minimum requirement.

**Comment by marksweb** [comment]
That's right @jrief

I looked over it & <3.5 appeared to have been removed so that became part of my checks for dropping old compatibility allowances 👍

**Pull request merged**
