### PR TITLE
Django 1.9 support, handling in list-sortable.js, disable reordering when list is unsorted, moving arbitrary number of pages.

### PR DESCRIPTION
**Pull request by teddybeermaniac**
Hi, when I played around with your application a little bit more I found that there are two bugs in list-sortable.js:

- when the first item was moved to the second position, moving it back without refreshing made no change (it was moved from second position again to the second position)
- when ordering was reversed moving an item one position down did nothing (check for item being dropped to its original position did not account for ordering)

So while I know next to nothing about JS :smile: I changed drag & drop handling so it should work properly now.

Also I made some changes adding django 1.9 support while hopefully not breaking anything.

### CODE REVIEW

**Comment by jrief** [comment]
Thanks for this great pull request. During the next days, I will test it locally in my environment.

@mkoistinen could you please review.

Thanks, Jacob

**Comment by teddybeermaniac** [comment]
I added two more commits, which disable drag & drop and moving between pages when list is not ordered by the draggable column, because IMO those actions don't make much sense when list is not ordered in the first place, also their results were rather unpredictable.

**Comment by jrief** [comment]
btw., do you have any idea how to order items if table becomes very long, say more than 10k objects. Even if we put 100 items per page, we have 100 pages. But adminsortable2 only allows to move them to the next or to the last page. On the other side I'd like to avoid a pull down action with too many ``move items to page 3``, ``move items to page 4``,..., ``move items to page 99``.

One way achieving this would be increase the steps. Say we are on page 50, then we can move up and down to page 46, 47, 48, 49, 51, 52, 53, 54 and additionally to page 10, 20, 30, 40, 60, 70, 80, 90.

This would keep the list of the pull down action menu at an acceptable length.

**Comment by teddybeermaniac** [comment]
I googled for "action with input django admin" and the [first result](http://agiliq.com/blog/2014/08/passing-parameters-to-django-admin-action/) looks promising. I may try to implement it, but as I just started learning/using django and stumbled upon your project when designing my first one, I'm not sure if I'll succeed. :)

Also I changed my previous two commits, as I did not notice that my changes in admin.py made list-sortable.js not being included at all, so checking ordering in it was not needed.

**Comment by jrief** [comment]
That look promising indeed!
Does the field "Price" disappear when the action points to something else than "update price for selected rows"? Anyway this can be achieved with a few lines of Javascript.

**Comment by teddybeermaniac** [comment]
Success! :smiley: I pushed changes to actions_input branch in my repo, see teddybeermaniac/django-admin-sortable2@9a5e60025b73908cbee19a974e826dae2fca8c39 for changes. If you'll like it I'll merge it back into master and update this PR.

The only think missing is some kind of notification for user if invalid page was specified and no action was taken.

**Comment by jrief** [comment]
I'm already very excited about patching this into my own applications. This was a feature I always missed a lot.
Thanks, Jacob

**Comment by jrief** [comment]
I just tested your code. I'v a list with 3 items. Whenever I move an item to the first position, I get this error:

in line 49 of list-sortable.js:
```
Uncaught TypeError: Cannot read property 'split' of undefined
```

any ideas?

**Comment by teddybeermaniac** [comment]
Yeah I reverted some changes to list-sortable.js, one which was check if `o` is in GET parameters. Fixed and merged everything into master branch.

**Comment by jrief** [comment]
Thanks you very much for these new features. I just released them as version 0.6.0.
Moving items to any arbitrary page is really, really useful.
Additionally I translated the new gettext-strings to German.

**Pull request merged**
